name: test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "00 15 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, 3.1]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install && bundle exec rake test
      - run: bundle install && bundle exec rake test:sinatra
        env:
          SINATRA: 2.2.4
      - run: bundle install && bundle exec rake test:sinatra
        env:
          SINATRA: 3.0.5
      #- run: bundle install && bundle exec rake test:rails
      #  env:
      #    RAILS: 7.0.4
      #- run: bundle install && bundle exec rake test:rails
      #  env:
      #    RAILS: 6.1.7
      #- run: bundle install && bundle exec rake test:rails
      #  env:
      #    RAILS: 6.0.6
      # - run: bundle install && bundle exec rake test:rails
      #   env:
      #     RAILS: 5.2.8
      # - run: bundle install && bundle exec rake test:rails
      #   env:
      #     RAILS: 5.1.7
      # - run: bundle install && bundle exec rake test:rails
      #   env:
      #     RAILS: 5.0.7
      # - run: bundle install && bundle exec rake test:rails
      #   env:
      #     RAILS: 4.2.11
